use [EXEMPLO_TABELA];
/*Exemplo de uso de cursor, recebendo duas colunas ou mais.*/
IF CURSOR_STATUS('global', 'CURSOR1') >= -1
BEGIN
	IF CURSOR_STATUS ('global', 'CURSOR1') > -1
	BEGIN
		CLOSE CURSOR1
	END
	DEALLOCATE CURSOR1
END
DECLARE @NOME_FUNCIONARIO VARCHAR (200)
DECLARE @MATRICULA_FUNCIONARIO VARCHAR(100)
DECLARE CURSOR1 CURSOR FOR SELECT TOP 5 NOME, MATRICULA  FROM [TABELA_DE_VENDEDORES]
OPEN CURSOR1
FETCH NEXT FROM CURSOR1 INTO @NOME_FUNCIONARIO, @MATRICULA_FUNCIONARIO
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT @NOME_FUNCIONARIO + ' ' + @MATRICULA_FUNCIONARIO
FETCH NEXT FROM CURSOR1 INTO @NOME_FUNCIONARIO, @MATRICULA_FUNCIONARIO
END
